export * from "./InfoDefault";
export * from "./CoverImage";
export * from "./InfoName";
export * from "./InfoLeft";
export * from "./InfoRight";
export * from "./Introduce";
export * from "./ImageInfo";
export * from "./FriendInfo";
export * from "./CardFriend";
